volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
