volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  web:
    build:
      context: ./app
    working_dir: /go/src/app
    volumes:
      - ./app:/go/src/app
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      PORT: 8080
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    command: go run ./cmd/web

  admin:
    build:
      context: ./app
    working_dir: /go/src/app
    volumes:
      - ./app:/go/src/app
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      PORT: 8081
    ports:
      - '8081:8081'
    depends_on:
      - postgres
    command: go run ./cmd/admin

