package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"github.com/kensei18/enechain-technical-assignment/app/graph/admin"
)

// Mutation returns admin.MutationResolver implementation.
func (r *Resolver) Mutation() admin.MutationResolver { return &mutationResolver{r} }

// Query returns admin.QueryResolver implementation.
func (r *Resolver) Query() admin.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
